site_name: Mkdocs 学习笔记
copyright: 'Copyright © 2021 Xiangjun Qu <xiangjunqu@foxmail.com>.'
repo_name: 'mkdocs-learning-note'
repo_url: 'https://github.com/Qu-Xiangjun/mkdocs-learning-note'

use_directory_urls: true # 让url的.html结尾消失，观感更好

theme:
  name: material
  features:
    - navigation.tabs

nav:
  - 主页: index.md
  - MkDocs 快速开始: quick_start/quick_start.md
  - 学习笔记:
    - 撰写文档: learning_note/write_docu.md
    - 配置主题: learning_note/configure_doc_theme.md
    - 自定义主题: learning_note/self_theme.md
    - 配置文件: learning_note/config_file.md
    - 部署文档: learning_note/deploy_docs.md
plugins:
  - search
markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true # 要在（内置的）toc扩展中启用永久链接